const productList = [
  {
    id: 1,
    name: "Mechanical Keyboard",
    category: "Keyboards",
    price: 150,
    stock: 45,
  },
  {
    id: 2,
    name: "Wireless Mouse",
    category: "Mice",
    price: 50,
    stock: 80,
  },
  {
    id: 3,
    name: "Gaming Headset",
    category: "Headsets",
    price: 120,
    stock: 60,
  },
  {
    id: 4,
    name: "Ethernet Cable (10m)",
    category: "Cables",
    price: 20,
    stock: 200,
  },
  {
    id: 5,
    name: "Wi-Fi Router",
    category: "Networking",
    price: 90,
    stock: 35,
  },
  {
    id: 6,
    name: "SSD External Drive (1TB)",
    category: "Storage",
    price: 110,
    stock: 50,
  },
  {
    id: 7,
    name: "USB-C Hub",
    category: "Accessories",
    price: 40,
    stock: 150,
  },
  {
    id: 8,
    name: "HDMI to VGA Adapter",
    category: "Adapters",
    price: 25,
    stock: 75,
  },
  {
    id: 9,
    name: "Portable Monitor",
    category: "Monitors",
    price: 250,
    stock: 30,
  },
  {
    id: 10,
    name: "Webcam (1080p)",
    category: "Cameras",
    price: 70,
    stock: 40,
  },
  {
    id: 11,
    name: "Bluetooth Speaker",
    category: "Audio",
    price: 85,
    stock: 100,
  },
  {
    id: 12,
    name: "Graphics Tablet",
    category: "Accessories",
    price: 200,
    stock: 15,
  },
  {
    id: 13,
    name: "Gaming Mouse Pad",
    category: "Accessories",
    price: 30,
    stock: 120,
  },
  {
    id: 14,
    name: "Mechanical Gaming Keyboard",
    category: "Keyboards",
    price: 180,
    stock: 50,
  },
  {
    id: 15,
    name: "Smart Power Strip",
    category: "Accessories",
    price: 60,
    stock: 75,
  },
  {
    id: 16,
    name: "Gaming Chair",
    category: "Furniture",
    price: 300,
    stock: 20,
  },
  {
    id: 17,
    name: "Monitor Stand",
    category: "Accessories",
    price: 35,
    stock: 110,
  },
  {
    id: 18,
    name: "USB-C Cable (2m)",
    category: "Cables",
    price: 15,
    stock: 300,
  },
  {
    id: 19,
    name: "Mechanical Numeric Keypad",
    category: "Keyboards",
    price: 50,
    stock: 85,
  },
  {
    id: 20,
    name: "Wireless Charging Pad",
    category: "Accessories",
    price: 45,
    stock: 70,
  },
];

export default productList;
